version: "3.9"
services:
  node-backend:
    image: ghcr.io/${GHCR_OWNER}/auth-node-backend:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./node-stack/backend/.env
    volumes:
      - ${AUTHELIA_USERS_FILE_HOST}:/data/users_database.yml
    ports:
      - "4100:4100"

  node-frontend:
    image: ghcr.io/${GHCR_OWNER}/auth-node-frontend:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - node-backend
    ports:
      - "3100:3100"

  python-backend:
    image: ghcr.io/${GHCR_OWNER}/auth-python-backend:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./python-stack/backend/.env
    volumes:
      - ${AUTHELIA_USERS_FILE_HOST}:/data/users_database.yml
    ports:
      - "5100:5100"

  python-frontend:
    image: ghcr.io/${GHCR_OWNER}/auth-python-frontend:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - python-backend
    ports:
      - "3200:3200"
